"use client";
/**
 * Journal feed — the campaign's running narrative, generated by
 * the AI GM. Ordered entries form the story timeline.
 */
import { useEffect, useState } from "react";
import { Markdown } from "@/components/gm/Markdown";

interface Entry {
  id: string;
  order: number;
  title: string;
  body: string;
  summary: string | null;
  createdAt: string;
}

export function JournalFeed({
  campaignId,
  refreshKey = 0,
}: {
  campaignId: string;
  refreshKey?: number;
}) {
  const [entries, setEntries] = useState<Entry[]>([]);
  const [selected, setSelected] = useState<Entry | null>(null);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    (async () => {
      const res = await fetch(`/api/campaigns/${campaignId}`);
      if (res.ok) {
        const data = await res.json();
        setEntries(data.campaign.journal);
      }
      setLoading(false);
    })();
  }, [campaignId, refreshKey]);

  if (loading) return <p className="p-6 text-sm text-ink-500">Loading…</p>;

  return (
    <div className="mx-auto max-w-3xl p-6">
      {entries.length === 0 ? (
        <p className="panel p-6 text-center text-sm text-ink-500">
          No journal entries yet. Play a scene — the GM writes the chronicle as you go.
        </p>
      ) : (
        <ol className="space-y-3">
          {entries.map((e) => (
            <li key={e.id}>
              <button
                className="panel block w-full px-4 py-3 text-left hover:border-ink-400"
                onClick={() => setSelected(e)}
              >
                <span className="mono mr-2 text-ink-400">#{e.order}</span>
                <span className="font-semibold">{e.title}</span>
                {e.summary && (
                  <p className="mt-1 text-sm text-ink-500">{e.summary}</p>
                )}
              </button>
            </li>
          ))}
        </ol>
      )}

      {/* Full entry modal */}
      {selected && (
        <div
          className="fixed inset-0 z-50 flex items-center justify-center bg-ink-950/50 p-6"
          onClick={() => setSelected(null)}
        >
          <article
            className="panel max-h-[80vh] w-full max-w-2xl overflow-y-auto bg-white"
            onClick={(e) => e.stopPropagation()}
          >
            <div className="panel-header">
              Journal #{selected.order} · {new Date(selected.createdAt).toLocaleDateString()}
            </div>
            <div className="p-6">
              <h2 className="font-serif text-2xl">{selected.title}</h2>
              <div className="mt-4 text-sm leading-relaxed">
                <Markdown>{selected.body}</Markdown>
              </div>
            </div>
          </article>
        </div>
      )}
    </div>
  );
}
